apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: opensearch-patched
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: opensearch-patched
spec:
  source:
    dockerfile: |
      FROM opensearchproject/opensearch:latest

      USER root

      RUN chmod -R 775 /usr/share/opensearch \
          && chmod +x /usr/share/opensearch/opensearch-docker-entrypoint.sh \
          && chgrp -R 0 /usr/share/opensearch

      USER 1001

  strategy:
    type: Docker

  output:
    to:
      kind: ImageStreamTag
      name: opensearch-patched:latest
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.opensearch.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1

  selector:
    matchLabels:
      app: opensearch

  template:
    metadata:
      labels:
        app: opensearch

    spec:
      containers:
      - name: opensearch

        image: image-registry.openshift-image-registry.svc:5000/{{ .Release.Namespace }}/opensearch-patched:latest

        imagePullPolicy: Always

        env:
          - name: discovery.type
            value: single-node

          - name: OPENSEARCH_JAVA_OPTS
            value: {{ .Values.opensearch.heap | quote }}

          ##################################################################
          # DISABLE SECURITY FOR HACKATHON / INTERNAL CLUSTER
          ##################################################################

          - name: DISABLE_SECURITY_PLUGIN
            value: "true"

          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"

          - name: bootstrap.memory_lock
            value: "false"
        ports:
        - containerPort: 9200

        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-storage

        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 120
          periodSeconds: 20

        securityContext:
          allowPrivilegeEscalation: false

        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"

      volumes:
      - name: opensearch-storage
        persistentVolumeClaim:
          claimName: opensearch-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch

  ports:
  - port: 9200
    targetPort: 9200
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opensearch
spec:
  to:
    kind: Service
    name: opensearch
  tls:
    termination: edge