apiVersion: v1
kind: Secret
metadata:
  name: observaai-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres
  GITHUB_TOKEN: changeme
  JIRA_API_TOKEN: changeme
  OPENSEARCH_ADMIN_PASSWORD: 09en$e@rC#
  GOOGLE_CLOUD_PROJECT_ID: db-dev-fwlg-tfai-int
  JIRA_URL: ""
  JIRA_USERNAME: ""