namespace: observaai

backend:
  image: image-registry.openshift-image-registry.svc:5000/observaai/observaai-backend:latest

frontend:
  image: image-registry.openshift-image-registry.svc:5000/observaai/observaai-frontend:latest

postgres:
  image: pgvector/pgvector:pg16
  storage: 2Gi

opensearch:
  image: opensearchproject/opensearch:latest
  storage: 2Gi
  heap: "-Xms256m -Xmx256m"

jira:
  image: docker.io/atlassian/jira-software:9.12
  storage: 5Gi

redis:
  image: redis:7-alpine

minio:
  image: quay.io/minio/minio
  storage: 2Gi


jira:
  enabled: false

redis:
  enabled: false

minio:
  enabled: false
