name: Backend CI/CD

on:
  workflow_dispatch:
  push:
    paths:
      - "app/**"
      - "requirements.txt"
      - "Dockerfile"

jobs:
  backend-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Validate Backend
        run: |
          python -m compileall app

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz

          tar -xzf oc.tar.gz

          chmod +x oc kubectl

          export PATH=$PATH:$(pwd)

          echo "$(pwd)" >> $GITHUB_PATH

          oc version

      - name: Login to OpenShift
        run: |
          mkdir -p $(pwd)/.kube

          export KUBECONFIG=$(pwd)/.kube/config

          oc login ${{ secrets.OPENSHIFT_SERVER }} \
            --token=${{ secrets.OPENSHIFT_TOKEN }} \
            --insecure-skip-tls-verify=true

          oc projects

      - name: Trigger Backend Build
        run: |
          oc start-build observaai-backend             --from-dir=.             --follow             -n ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Rollout Backend
        run: |
          oc rollout restart deployment/observaai-backend             -n ${{ secrets.OPENSHIFT_NAMESPACE }}
