name: Deploy ObservaAI Platform

on:
  workflow_dispatch:

jobs:
  deploy-platform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_API }}             --token=${{ secrets.OPENSHIFT_TOKEN }}             --insecure-skip-tls-verify=true

      - name: Create Namespace
        run: |
          oc new-project ${{ secrets.OPENSHIFT_NAMESPACE }} || true

      - name: Create GCP Secret
        run: |
          echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > key.json

          oc create secret generic gcp-service-account             --from-file=key.json             -n ${{ secrets.OPENSHIFT_NAMESPACE }}             --dry-run=client -o yaml | oc apply -f -

      - name: Deploy Platform
        run: |
          helm upgrade --install observaai-platform             infra/helm/observaai-platform             --namespace=${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Wait For Core Infra
        run: |
          oc rollout status deployment/postgres -n ${{ secrets.OPENSHIFT_NAMESPACE }}
          oc rollout status deployment/opensearch -n ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Wait For Backend
        run: |
          oc rollout status deployment/observaai-backend -n ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Wait For Frontend
        run: |
          oc rollout status deployment/observaai-frontend -n ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Optional Jira Validation
        run: |
          oc get deployment jira -n ${{ secrets.OPENSHIFT_NAMESPACE }} || true

      - name: Validate Routes
        run: |
          oc get routes -n ${{ secrets.OPENSHIFT_NAMESPACE }}